### ISSUE TITLE
How do I run this on the discord server instead of my PC?

### ISSUE THREAD

**Issue by Mustang2049** [Khaazz/Cross-Server-Bot#3]
Hello, I have managed to get the bot up and running, but whenever I start it and close the powershell, this stops the bot. How do I keep it running without having to start it from the command line every time?

**Comment by bsian03** [comment]
Use [PM2](http://pm2.keymetrics.io/), run `pm2 start filename.js`, restart would be `pm2 restart name` and stop would be `pm2 stop name`

**Comment by Mustang2049** [comment]
How exactly do I do that? When I use npm pm2start, it doesn't accept that command.

**Comment by bsian03** [comment]
That's because
1: I didn't say run `npm pm2start`
2: npm is a **n**ode **p**ackage **m**anager

**Comment by Mustang2049** [comment]
Ok, but in the bot, what is filename. js? There's index.js and resolve.js

**Comment by bsian03** [comment]
What file do you start the bot with?

**Comment by Mustang2049** [comment]
I use the command npm start in Windows PowerShell.
I cloned the repository in a GitHub file.

**Comment by bsian03** [comment]
Oh I see. Then it'll be `pm2 start index.js`

**Comment by Mustang2049** [comment]
Ok, I'll try that!

**Comment by Mustang2049** [comment]
Unfortunately, it DID work, but I want it to work without me having to have my system run all the time without having to keep PowerShell open.

**Comment by bsian03** [comment]
Well... host your bot somewhere.

**Comment by Mustang2049** [comment]
How exactly do I do that?

**Comment by Mustang2049** [comment]
I host my bot on three servers to connect thm via one channel.

**Comment by Protegus** [comment]
No... Host your bot somewhere. Glitch, AWS, LOC, etc. There are many resources. Google it.

**Comment by Mustang2049** [comment]
Oh, that is what you meant. Ok, I'll try it.

**Comment by bsian03** [comment]
That's not hosting. Hosting means to run whatever you are running on a computer. Like right now, you're hosting on your computer. I'm saying host your files somewhere you don't need to turn the computer off

**Comment by Mustang2049** [comment]
Yeah, that was what I was thinking. I will try Glitch and will let you know if it works. Thanks!

**Comment by VoidNulll** [comment]
That is in no way how hosting works.

A Host is (generally) a completely seperate computer than your own that is meant to run 24/7, it has a seperate operating system
You can find hosts such as DigitalOcean and Vultr for as little as $5 a month (you can find youtube videos).
These hosts require something called SSH to access them (there are videos on this).

Once you have a host setup, you would host your bot the same way you do on your pc. Most of the time you will not have a graphical user interface like your normal computer has, and will have to be somewhat familiar (like around novice) and know basic commands for whatever command line you pick.

Also most latest windows builds come with ssh in powershell, and if it doesn't you can use something called Putty.

**Comment by Mustang2049** [comment]
Oh, thanks! That's what I'm looking for. And I am kind of experienced with the command line.

**Comment by VoidNulll** [comment]
Ok, as well as there are some free options with the one i know best being Library of Code™. There is glitch but in anyones eye who have used an actual vps that is just pure garbage.

Also free vps are usually shared with other users so keep that in mind... Also i believe AWS has a free tier, but you need a credit card for that and need to cancel, its also a pain to get data. But if you are not storing data it might be fine, for a year

**Comment by Khaazz** [comment]
Just to clarify on this one, you got pretty much everything here. We will keep it to the discord server for further questions related to hosting.

I would also add that as mentionned before I wouldn't go for glitch for a discord bot. There are free tiers available with GCP or AWS for example. For other solution (eg: Library Of Code), we will get you in the discord.
Hope you get everything to work as you intend to :ok_hand:

**Comment by VoidNulll** [comment]
Thanks KhaaZ

**Comment by bsian03** [comment]
I'll buy you a baguette

**Comment by VoidNulll** [comment]
Bsian we already have one, and thats human trafficking..
Last i checked human trafficking was illegal in most countries.

**Comment by bsian03** [comment]
I already know where he is though

**Comment by Mustang2049** [comment]
Thank you very much!

**Comment by Bossaidy** [comment]
k
