### ISSUE TITLE
Bot not starting - npm and Node.js both up to date on ubuntu 16.04.6 LTS [Debug log attached] 

### ISSUE THREAD

**Issue by vesturo** [Khaazz/Cross-Server-Bot#4]
root@localhost:/cross# npm start index.js

> cross-server-bot@1.0.0 start /cross
> node index.js "index.js"

sh: 1: node: not found

npm ERR! Linux 4.4.0
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "index.js"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cross-server-bot@1.0.0 start: `node index.js "index.js"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the cross-server-bot@1.0.0 start script 'node index.js "index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cross-server-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js "index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cross-server-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cross-server-bot
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /cross/npm-debug.log
root@localhost:/cross#
[npm-debug.log](https://github.com/Khaazz/Cross-Server-Bot/files/3772137/npm-debug.log)

**Comment by bsian03** [comment]
You're trying to start the bot using the node package manager... that is not what you want.
`node file.js` is what you need to run to start a node process.
I'd highly recommend you take a look at the difference because it will get you so far in the world of development

**Comment by vesturo** [comment]
.... I fe retarded right now... Thanks haha how tf did I not figure that out LOL

**Comment by vesturo** [comment]
Nevermind, another error I can't explain now.


Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Kata Containers are now fully integrated in Charmed Kubernetes 1.16!
   Yes, charms take the Krazy out of K8s Kata Kluster Konstruction.

     https://ubuntu.com/kubernetes/docs/release-notes
Last login: Fri Oct 25 15:56:34 2019 from 46.89.136.138
root@localhost:~# cd /cross
root@localhost:/cross# node index.js
/cross/index.js:169
async function triggerWH(channel, user, content) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
root@localhost:/cross#

**Comment by bsian03** [comment]
Run `node -v` and tell me what it gives you

**Comment by vesturo** [comment]
V.2.4.6 is the only output

**Comment by bsian03** [comment]
You're on a very old version of node.

**Comment by bsian03** [comment]
There's been up to 10 major updates to node compared to the version you're using

**Comment by Khaazz** [comment]
Yeah this issue is in no way related to this project but with your node / ubuntu install.
I am closing this now, we continued to take care of this in our support server anyway.
